print ("BBBBBBB                A")       
print ("B      B              A  A")
print ("B       B            A    A")
print ("B      B            A      A")
print ("BBBBBBB            A        A")
print ("B      B          AAAAAAAAAAAA")
print ("B       B        A            A")
print ("B      B        A              A") 
print ("BBBBBBB        A                A") 